<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SUKTOAE" failures="7" tests="11" name="PetTest" time="13.576" errors="0" timestamp="2023-11-28T13:18:20 GMT">
  <testcase classname="api.tests.DDTests" name="testPostUser" time="2.359">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void api.tests.DDTests.testPostUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testPostUser([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7])
Arguments: [(java.lang.String) 1010,(java.lang.String) tester11,(java.lang.String) Rob,(java.lang.String) Don,(java.lang.String) test1@gmail.com,(java.lang.String) Test@1,(java.lang.String) 123456789]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void api.tests.DDTests.testPostUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testPostUser([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7])
Arguments: [(java.lang.String) 1010,(java.lang.String) tester11,(java.lang.String) Rob,(java.lang.String) Don,(java.lang.String) test1@gmail.com,(java.lang.String) Test@1,(java.lang.String) 123456789]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="3.827">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.537">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.528">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="0.554">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="0.518">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="0.52">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.UserTests" name="testPostUser" time="1.22"/>
  <testcase classname="api.tests.UserTests" name="testGetUserByName" time="0.565"/>
  <testcase classname="api.tests.UserTests" name="testUpdateUserByName" time="1.048"/>
  <testcase classname="api.tests.UserTests" name="testDeleteUserByName" time="0.512"/>
</testsuite> <!-- PetTest -->
